---
title: "Lab 10"
author: "Audrey Omidsalar"
date: "11/5/2021"
output:
  html_document:
    toc: yes
    toc_float: yes
    keep_md: yes
  github_document:
  always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('RSQLite')
library('DBI')
```

## Setup
```{r downloading}
# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")
# Download tables
actor <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/actor.csv")
rental <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/rental.csv")
customer <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/customer.csv")
payment <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/payment_p2007_01.csv")

# Copy data.frames to database
dbWriteTable(con, "actor", actor)
dbWriteTable(con, "rental", rental)
dbWriteTable(con, "customer", customer)
dbWriteTable(con, "payment", payment)
```
List tables
```{r list-tables}
dbListTables(con)
```
#### Getting information about the *actor* table
```{r pragma}
dbGetQuery(con ,"PRAGMA table_info(actor)")
```

## Exercise 1

Retrieve the actor ID, first name and last name for all actors using the actor table. Sort by last name and then by first name. Use LIMIT (head() in R) to output the top 5.

```{r ex1}
dbGetQuery(con , "SELECT actor_id, first_name, last_name
FROM actor
ORDER by last_name, first_name /* comments can be added
on multiple lines like this */
LIMIT 5")
```

## Exercise 2

```{r ex2}
dbGetQuery(con, "SELECT actor_id, first_name, last_name
FROM actor
WHERE last_name IN ('WILLIAMS', 'DAVIS')")
```

## Exercise 3

```{r}
dbGetQuery(con, "SELECT DISTINCT customer_id
FROM rental
WHERE date(rental_date)= '2005-07-05'
")
```

## Exercise 4

```{r}
q <- dbSendQuery(con, "SELECT *
FROM payment
WHERE amount IN (1.99, 7.99, 9.99)")
dbFetch(q, n=10)
##fetch query to get results in 10-row chunks
```

